export const countries = [
    { value: 'AF', label: 'Afghanistan', countryCode: '93' },
    { value: 'AL', label: 'Albania', countryCode: '355' },
    { value: 'DZ', label: 'Algeria', countryCode: '213' },
    { value: 'AD', label: 'Andorra', countryCode: '376' },
    { value: 'AO', label: 'Angola', countryCode: '244' },
    { value: 'AG', label: 'Antigua and Barbuda', countryCode: '1-268' },
    { value: 'AR', label: 'Argentina', countryCode: '54' },
    { value: 'AM', label: 'Armenia', countryCode: '374' },
    { value: 'AU', label: 'Australia', countryCode: '61' },
    { value: 'AT', label: 'Austria', countryCode: '43' },
    { value: 'AZ', label: 'Azerbaijan', countryCode: '994' },
    { value: 'BS', label: 'Bahamas', countryCode: '1-242' },
    { value: 'BH', label: 'Bahrain', countryCode: '973' },
    { value: 'BD', label: 'Bangladesh', countryCode: '880' },
    { value: 'BB', label: 'Barbados', countryCode: '1-246' },
    { value: 'BY', label: 'Belarus', countryCode: '375' },
    { value: 'BE', label: 'Belgium', countryCode: '32' },
    { value: 'BZ', label: 'Belize', countryCode: '501' },
    { value: 'BJ', label: 'Benin', countryCode: '229' },
    { value: 'BT', label: 'Bhutan', countryCode: '975' },
    { value: 'BO', label: 'Bolivia', countryCode: '591' },
    { value: 'BA', label: 'Bosnia and Herzegovina', countryCode: '387' },
    { value: 'BW', label: 'Botswana', countryCode: '267' },
    { value: 'BR', label: 'Brazil', countryCode: '55' },
    { value: 'BN', label: 'Brunei', countryCode: '673' },
    { value: 'BG', label: 'Bulgaria', countryCode: '359' },
    { value: 'BF', label: 'Burkina Faso', countryCode: '226' },
    { value: 'BI', label: 'Burundi', countryCode: '257' },
    { value: 'CV', label: 'Cabo Verde', countryCode: '238' },
    { value: 'KH', label: 'Cambodia', countryCode: '855' },
    { value: 'CM', label: 'Cameroon', countryCode: '237' },
    { value: 'CA', label: 'Canada', countryCode: '1' },
    { value: 'CF', label: 'Central African Republic', countryCode: '236' },
    { value: 'TD', label: 'Chad', countryCode: '235' },
    { value: 'CL', label: 'Chile', countryCode: '56' },
    { value: 'CN', label: 'China', countryCode: '86' },
    { value: 'CO', label: 'Colombia', countryCode: '57' },
    { value: 'KM', label: 'Comoros', countryCode: '269' },
    { value: 'CD', label: 'Congo (Democratic Republic)', countryCode: '243' },
    { value: 'CG', label: 'Congo (Republic)', countryCode: '242' },
    { value: 'CR', label: 'Costa Rica', countryCode: '506' },
    { value: 'CI', label: "Cote d'Ivoire", countryCode: '225' },
    { value: 'HR', label: 'Croatia', countryCode: '385' },
    { value: 'CU', label: 'Cuba', countryCode: '53' },
    { value: 'CY', label: 'Cyprus', countryCode: '357' },
    { value: 'CZ', label: 'Czech Republic', countryCode: '420' },
    { value: 'DK', label: 'Denmark', countryCode: '45' },
    { value: 'DJ', label: 'Djibouti', countryCode: '253' },
    { value: 'DM', label: 'Dominica', countryCode: '1-767' },
    { value: 'DO', label: 'Dominican Republic', countryCode: '1-809, 1-829, 1-849' },
    { value: 'TL', label: 'East Timor (Timor-Leste)', countryCode: '670' },
    { value: 'EC', label: 'Ecuador', countryCode: '593' },
    { value: 'EG', label: 'Egypt', countryCode: '20' },
    { value: 'SV', label: 'El Salvador', countryCode: '503' },
    { value: 'GQ', label: 'Equatorial Guinea', countryCode: '240' },
    { value: 'ER', label: 'Eritrea', countryCode: '291' },
    { value: 'EE', label: 'Estonia', countryCode: '372' },
    { value: 'SZ', label: 'Eswatini (formerly Swaziland)', countryCode: '268' },
    { value: 'ET', label: 'Ethiopia', countryCode: '251' },
    { value: 'FJ', label: 'Fiji', countryCode: '679' },
    { value: 'FI', label: 'Finland', countryCode: '358' },
    { value: 'FR', label: 'France', countryCode: '33' },
    { value: 'GA', label: 'Gabon', countryCode: '241' },
    { value: 'GM', label: 'Gambia', countryCode: '220' },
    { value: 'GE', label: 'Georgia', countryCode: '995' },
    { value: 'DE', label: 'Germany', countryCode: '49' },
    { value: 'GH', label: 'Ghana', countryCode: '233' },
    { value: 'GR', label: 'Greece', countryCode: '30' },
    { value: 'GD', label: 'Grenada', countryCode: '1-473' },
    { value: 'GT', label: 'Guatemala', countryCode: '502' },
    { value: 'GN', label: 'Guinea', countryCode: '224' },
    { value: 'GW', label: 'Guinea-Bissau', countryCode: '245' },
    { value: 'GY', label: 'Guyana', countryCode: '592' },
    { value: 'HT', label: 'Haiti', countryCode: '509' },
    { value: 'HN', label: 'Honduras', countryCode: '504' },
    { value: 'HU', label: 'Hungary', countryCode: '36' },
    { value: 'IS', label: 'Iceland', countryCode: '354' },
    { value: 'IN', label: 'India', countryCode: '91' },
    { value: 'ID', label: 'Indonesia', countryCode: '62' },
    { value: 'IR', label: 'Iran', countryCode: '98' },
    { value: 'IQ', label: 'Iraq', countryCode: '964' },
    { value: 'IE', label: 'Ireland', countryCode: '353' },
    { value: 'IL', label: 'Israel', countryCode: '972' },
    { value: 'IT', label: 'Italy', countryCode: '39' },
    { value: 'JM', label: 'Jamaica', countryCode: '1-876' },
    { value: 'JP', label: 'Japan', countryCode: '81' },
    { value: 'JO', label: 'Jordan', countryCode: '962' },
    { value: 'KZ', label: 'Kazakhstan', countryCode: '7' },
    { value: 'KE', label: 'Kenya', countryCode: '254' },
    { value: 'KI', label: 'Kiribati', countryCode: '686' },
    { value: 'XK', label: 'Kosovo', countryCode: '383' },
    { value: 'KW', label: 'Kuwait', countryCode: '965' },
    { value: 'KG', label: 'Kyrgyzstan', countryCode: '996' },
    { value: 'LA', label: 'Laos (Lao People\'s Democratic Republic)', countryCode: '856' },
    { value: 'LV', label: 'Latvia', countryCode: '371' },
    { value: 'LB', label: 'Lebanon', countryCode: '961' },
    { value: 'LS', label: 'Lesotho', countryCode: '266' },
    { value: 'LR', label: 'Liberia', countryCode: '231' },
    { value: 'LY', label: 'Libya', countryCode: '218' },
    { value: 'LI', label: 'Liechtenstein', countryCode: '423' },
    { value: 'LT', label: 'Lithuania', countryCode: '370' },
    { value: 'LU', label: 'Luxembourg', countryCode: '352' },
    { value: 'MG', label: 'Madagascar', countryCode: '261' },
    { value: 'MW', label: 'Malawi', countryCode: '265' },
    { value: 'MY', label: 'Malaysia', countryCode: '60' },
    { value: 'MV', label: 'Maldives', countryCode: '960' },
    { value: 'ML', label: 'Mali', countryCode: '223' },
    { value: 'MT', label: 'Malta', countryCode: '356' },
    { value: 'MH', label: 'Marshall Islands', countryCode: '692' },
    { value: 'MR', label: 'Mauritania', countryCode: '222' },
    { value: 'MU', label: 'Mauritius', countryCode: '230' },
    { value: 'MX', label: 'Mexico', countryCode: '52' },
    { value: 'FM', label: 'Micronesia', countryCode: '691' },
    { value: 'MD', label: 'Moldova', countryCode: '373' },
    { value: 'MC', label: 'Monaco', countryCode: '377' },
    { value: 'MN', label: 'Mongolia', countryCode: '976' },
    { value: 'ME', label: 'Montenegro', countryCode: '382' },
    { value: 'MA', label: 'Morocco', countryCode: '212' },
    { value: 'MZ', label: 'Mozambique', countryCode: '258' },
    { value: 'MM', label: 'Myanmar', countryCode: '95' },
    { value: 'NA', label: 'Namibia', countryCode: '264' },
    { value: 'NR', label: 'Nauru', countryCode: '674' },
    { value: 'NP', label: 'Nepal', countryCode: '977' },
    { value: 'NL', label: 'Netherlands', countryCode: '31' },
    { value: 'NZ', label: 'New Zealand', countryCode: '64' },
    { value: 'NI', label: 'Nicaragua', countryCode: '505' },
    { value: 'NE', label: 'Niger', countryCode: '227' },
    { value: 'NG', label: 'Nigeria', countryCode: '234' },
    { value: 'MK', label: 'North Macedonia', countryCode: '389' },
    { value: 'KP', label: 'North Korea', countryCode: '850' },
    { value: 'NO', label: 'Norway', countryCode: '47' },
    { value: 'OM', label: 'Oman', countryCode: '968' },
    { value: 'PK', label: 'Pakistan', countryCode: '92' },
    { value: 'PW', label: 'Palau', countryCode: '680' },
    { value: 'PA', label: 'Panama', countryCode: '507' },
    { value: 'PG', label: 'Papua New Guinea', countryCode: '675' },
    { value: 'PY', label: 'Paraguay', countryCode: '595' },
    { value: 'PE', label: 'Peru', countryCode: '51' },
    { value: 'PH', label: 'Philippines', countryCode: '63' },
    { value: 'PL', label: 'Poland', countryCode: '48' },
    { value: 'PT', label: 'Portugal', countryCode: '351' },
    { value: 'QA', label: 'Qatar', countryCode: '974' },
    { value: 'RO', label: 'Romania', countryCode: '40' },
    { value: 'RU', label: 'Russia', countryCode: '7' },
    { value: 'RW', label: 'Rwanda', countryCode: '250' },
    { value: 'KN', label: 'Saint Kitts and Nevis', countryCode: '1-869' },
    { value: 'LC', label: 'Saint Lucia', countryCode: '1-758' },
    { value: 'VC', label: 'Saint Vincent and the Grenadines', countryCode: '1-784' },
    { value: 'WS', label: 'Samoa', countryCode: '685' },
    { value: 'SM', label: 'San Marino', countryCode: '378' },
    { value: 'ST', label: 'Sao Tome and Principe', countryCode: '239' },
    { value: 'SA', label: 'Saudi Arabia', countryCode: '966' },
    { value: 'SN', label: 'Senegal', countryCode: '221' },
    { value: 'RS', label: 'Serbia', countryCode: '381' },
    { value: 'SC', label: 'Seychelles', countryCode: '248' },
    { value: 'SL', label: 'Sierra Leone', countryCode: '232' },
    { value: 'SG', label: 'Singapore', countryCode: '65' },
    { value: 'SK', label: 'Slovakia', countryCode: '421' },
    { value: 'SI', label: 'Slovenia', countryCode: '386' },
    { value: 'SB', label: 'Solomon Islands', countryCode: '677' },
    { value: 'SO', label: 'Somalia', countryCode: '252' },
    { value: 'ZA', label: 'South Africa', countryCode: '27' },
    { value: 'KR', label: 'South Korea', countryCode: '82' },
    { value: 'SS', label: 'South Sudan', countryCode: '211' },
    { value: 'ES', label: 'Spain', countryCode: '34' },
    { value: 'LK', label: 'Sri Lanka', countryCode: '94' },
    { value: 'SD', label: 'Sudan', countryCode: '249' },
    { value: 'SR', label: 'Suriname', countryCode: '597' },
    { value: 'SE', label: 'Sweden', countryCode: '46' },
    { value: 'CH', label: 'Switzerland', countryCode: '41' },
    { value: 'SY', label: 'Syria', countryCode: '963' },
    { value: 'TW', label: 'Taiwan', countryCode: '886' },
    { value: 'TJ', label: 'Tajikistan', countryCode: '992' },
    { value: 'TZ', label: 'Tanzania', countryCode: '255' },
    { value: 'TH', label: 'Thailand', countryCode: '66' },
    { value: 'TG', label: 'Togo', countryCode: '228' },
    { value: 'TO', label: 'Tonga', countryCode: '676' },
    { value: 'TT', label: 'Trinidad and Tobago', countryCode: '1-868' },
    { value: 'TN', label: 'Tunisia', countryCode: '216' },
    { value: 'TR', label: 'Turkey', countryCode: '90' },
    { value: 'TM', label: 'Turkmenistan', countryCode: '993' },
    { value: 'TV', label: 'Tuvalu', countryCode: '688' },
    { value: 'UG', label: 'Uganda', countryCode: '256' },
    { value: 'UA', label: 'Ukraine', countryCode: '380' },
    { value: 'AE', label: 'United Arab Emirates', countryCode: '971' },
    { value: 'GB', label: 'United Kingdom', countryCode: '44' },
    { value: 'US', label: 'United States', countryCode: '1' },
    { value: 'UY', label: 'Uruguay', countryCode: '598' },
    { value: 'UZ', label: 'Uzbekistan', countryCode: '998' },
    { value: 'VU', label: 'Vanuatu', countryCode: '678' },
    { value: 'VA', label: 'Vatican City', countryCode: '379' },
    { value: 'VE', label: 'Venezuela', countryCode: '58' },
    { value: 'VN', label: 'Vietnam', countryCode: '84' },
    { value: 'YE', label: 'Yemen', countryCode: '967' },
    { value: 'ZM', label: 'Zambia', countryCode: '260' },
    { value: 'ZW', label: 'Zimbabwe', countryCode: '263' }
  ];